export const STUDENTS = [
  {
    id: 1,
    name: "Adapala Thirumala, Shri Harsha",
    userid: "sadapala",
    office: "DAVIS 309 Desk 12",
    advisor1: "qiao",
    advisor2: "",
    funding: "Research Asst",
    fundingEditor: "cwmiller",
    fundingDate: "2025-11-14 17:20:40",
    initials: "AT",
  },
  {
    id: 2,
    name: "Ahmad, Harris",
    userid: "harrisah",
    office: "DAVIS 338Y",
    advisor1: "haonanlu",
    advisor2: "",
    funding: "Research Asst",
    fundingEditor: "carryfwd",
    fundingDate: "2025-10-09 09:14:22",
    initials: "HA",
  },
  {
    id: 3,
    name: "Chen, Wei",
    userid: "wchen42",
    office: "DAVIS 301B",
    advisor1: "fangliu",
    advisor2: "kzhang",
    funding: "Teaching Asst",
    fundingEditor: "jmorris",
    fundingDate: "2025-09-01 08:00:00",
    initials: "WC",
  },
  {
    id: 4,
    name: "Patel, Nisha Ramesh",
    userid: "nrpatel",
    office: "BELL 242",
    advisor1: "svlakshm",
    advisor2: "",
    funding: "Fellowship",
    fundingEditor: "cwmiller",
    fundingDate: "2025-08-25 11:30:00",
    initials: "NP",
  },
  {
    id: 5,
    name: "Okafor, Emmanuel Chidi",
    userid: "ecokafor",
    office: "DAVIS 310A",
    advisor1: "bsun",
    advisor2: "mpaul",
    funding: "Research Asst",
    fundingEditor: "carryfwd",
    fundingDate: "2025-11-01 14:10:05",
    initials: "EO",
  },
  {
    id: 6,
    name: "Kim, Jisoo",
    userid: "jkim88",
    office: "DAVIS 305",
    advisor1: "dpeng",
    advisor2: "",
    funding: "Teaching Asst",
    fundingEditor: "jmorris",
    fundingDate: "2025-09-15 09:45:00",
    initials: "JK",
  },
  {
    id: 7,
    name: "Ramirez, Sofia Elena",
    userid: "seramire",
    office: "BELL 115",
    advisor1: "qiao",
    advisor2: "bsun",
    funding: "Fellowship",
    fundingEditor: "cwmiller",
    fundingDate: "2025-10-20 16:00:00",
    initials: "SR",
  },
  {
    id: 8,
    name: "Nguyen, Thanh Duc",
    userid: "tdnguyen",
    office: "DAVIS 322",
    advisor1: "fangliu",
    advisor2: "",
    funding: "Research Asst",
    fundingEditor: "carryfwd",
    fundingDate: "2025-09-28 10:22:00",
    initials: "TN",
  },
  {
    id: 9,
    name: "Singh, Priya Anand",
    userid: "pasingh",
    office: "DAVIS 307",
    advisor1: "haonanlu",
    advisor2: "dpeng",
    funding: "Teaching Asst",
    fundingEditor: "jmorris",
    fundingDate: "2025-08-30 13:00:00",
    initials: "PS",
  },
  {
    id: 10,
    name: "Williams, Marcus J.",
    userid: "mjwilli",
    office: "BELL 240",
    advisor1: "svlakshm",
    advisor2: "",
    funding: "Research Asst",
    fundingEditor: "cwmiller",
    fundingDate: "2025-11-05 08:55:00",
    initials: "MW",
  },
  {
    id: 11,
    name: "Zhao, Lingzhi",
    userid: "lzhao7",
    office: "DAVIS 303",
    advisor1: "kzhang",
    advisor2: "",
    funding: "Fellowship",
    fundingEditor: "jmorris",
    fundingDate: "2025-10-12 12:10:00",
    initials: "ZL",
  },
  {
    id: 12,
    name: "Fernandez, Carlos A.",
    userid: "caferna",
    office: "DAVIS 318",
    advisor1: "mpaul",
    advisor2: "fangliu",
    funding: "Research Asst",
    fundingEditor: "carryfwd",
    fundingDate: "2025-09-03 15:45:00",
    initials: "CF",
  },
  {
    id: 13,
    name: "Lee, Seungwon",
    userid: "swlee",
    office: "BELL 130",
    advisor1: "dpeng",
    advisor2: "haonanlu",
    funding: "Teaching Asst",
    fundingEditor: "cwmiller",
    fundingDate: "2025-08-19 07:30:00",
    initials: "LS",
  },
  {
    id: 14,
    name: "Gupta, Rohan Vikram",
    userid: "rvgupta",
    office: "DAVIS 302",
    advisor1: "bsun",
    advisor2: "",
    funding: "Research Asst",
    fundingEditor: "jmorris",
    fundingDate: "2025-10-30 17:00:00",
    initials: "RG",
  },
  {
    id: 15,
    name: "Taylor, Brianna K.",
    userid: "bktaylo",
    office: "DAVIS 315",
    advisor1: "qiao",
    advisor2: "",
    funding: "Fellowship",
    fundingEditor: "carryfwd",
    fundingDate: "2025-11-10 09:00:00",
    initials: "BT",
  },
];

export const AVATAR_COLORS = [
  "#005bbb", "#1a73d4", "#003f84", "#0c4a6e", "#1e3a6e",
  "#065f46", "#7c3aed", "#b45309", "#be185d", "#0f766e",
];
